---

- hosts: all
  become: true
  tasks:


  - name: update repository index
    dnf:
      update_cache: yes

  - name: install apache2 package (httpd on centos 8+)
    dnf:
      name: httpd
      state: absent


  
  
